const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{Image: 0},
	{Платформер: 0},
	{Image2: 0},
	{r: 0},
	{l: 0},
	{Image5: 0},
	{Мышь: 0},
	{top: 0},
	{Bottom: 0},
	{Твёрдый: 0},
	{Image3: 0},
	{Клавиатура: 0},
	{Image4: 0},
	{Image6: 0},
	{Image7: 0},
	{Спрайт: 0},
	{score: 0},
	{Текст: 0},
	{ScoreFinal: 0},
	{Текст2: 0},
	{BestScoreFinal: 0},
	{Пуля: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{plate: 0},
	{Аудио: 0},
	{skin: 0},
	{maxSkin: 0},
	{game: 0},
	{SCORE: 0},
	{BestScore: 0},
	{Spawn: 0},
	{звук: 0}
];

self.InstanceType = {
	Image: class extends self.ISpriteInstance {},
	Image2: class extends self.ISpriteInstance {},
	r: class extends self.ISpriteInstance {},
	l: class extends self.ISpriteInstance {},
	Image5: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	top: class extends self.ISpriteInstance {},
	Bottom: class extends self.ISpriteInstance {},
	Image3: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	Image4: class extends self.ISpriteInstance {},
	Image6: class extends self.ISpriteInstance {},
	Image7: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	Текст: class extends self.ITextInstance {},
	ScoreFinal: class extends self.ITextInstance {},
	Текст2: class extends self.ITextInstance {},
	BestScoreFinal: class extends self.ITextInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	plate: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {}
}