const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Behaviors.Rotate,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Platform.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{Image: 0},
	{Image2: 0},
	{Image3: 0},
	{Image4: 0},
	{Image6: 0},
	{Image7: 0},
	{Image8: 0},
	{Твёрдый: 0},
	{Image9: 0},
	{Image10: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Image11: 0},
	{Клавиатура: 0},
	{Image12: 0},
	{Image13: 0},
	{Image14: 0},
	{Image15: 0},
	{Синусоида: 0},
	{fly: 0},
	{LeftPoint: 0},
	{RightPoint: 0},
	{Якорь: 0},
	{ТекстДляМух: 0},
	{МухаМеню: 0},
	{portal: 0},
	{ТайловыйФон: 0},
	{Image18: 0},
	{Image19: 0},
	{Мышь: 0},
	{Image20: 0},
	{Image21: 0},
	{Image22: 0},
	{Image23: 0},
	{Image24: 0},
	{Image25: 0},
	{Image26: 0},
	{Image27: 0},
	{Image28: 0},
	{Image29: 0},
	{Image30: 0},
	{Image5: 0},
	{Image31: 0},
	{Image32: 0},
	{Image33: 0},
	{Image34: 0},
	{Image35: 0},
	{Image36: 0},
	{Image37: 0},
	{Image38: 0},
	{Image39: 0},
	{Image40: 0},
	{Image41: 0},
	{Image42: 0},
	{Image43: 0},
	{DialogBg: 0},
	{Спрайт: 0},
	{DialogText: 0},
	{doorbell: 0},
	{mamcat: 0},
	{door: 0},
	{green_frog: 0},
	{green_frog_button: 0},
	{purple_frog_button: 0},
	{blue_frog_button: 0},
	{purple_frog: 0},
	{blue_frog: 0},
	{Текст: 0},
	{PricePinkFrog: 0},
	{PriceBlueFrog: 0},
	{button2: 0},
	{balanceText: 0},
	{Image16: 0},
	{Image17: 0},
	{Image44: 0},
	{cactus: 0},
	{Image46: 0},
	{Image47: 0},
	{Image48: 0},
	{Image49: 0},
	{Image50: 0},
	{Image51: 0},
	{Image52: 0},
	{Image53: 0},
	{cactus2: 0},
	{Image54: 0},
	{Image45: 0},
	{Image55: 0},
	{Image56: 0},
	{Image57: 0},
	{Image58: 0},
	{Image59: 0},
	{Image60: 0},
	{Image61: 0},
	{Поворот: 0},
	{Image62: 0},
	{Image63: 0},
	{Image64: 0},
	{Image65: 0},
	{Image66: 0},
	{Image67: 0},
	{Image68: 0},
	{Image69: 0},
	{Image70: 0},
	{Image71: 0},
	{Аудио: 0},
	{Image72: 0},
	{countFly: 0},
	{lvl: 0},
	{countFlyLvl: 0},
	{dialogueStage: 0},
	{cuurrentSkin: 0},
	{blueFrog: 0},
	{pinkFrog: 0}
];

self.InstanceType = {
	Image: class extends self.ISpriteInstance {},
	Image2: class extends self.ISpriteInstance {},
	Image3: class extends self.ISpriteInstance {},
	Image4: class extends self.ISpriteInstance {},
	Image6: class extends self.ISpriteInstance {},
	Image7: class extends self.ISpriteInstance {},
	Image8: class extends self.ISpriteInstance {},
	Image9: class extends self.ISpriteInstance {},
	Image10: class extends self.ISpriteInstance {},
	Image11: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	Image12: class extends self.ISpriteInstance {},
	Image13: class extends self.ISpriteInstance {},
	Image14: class extends self.ISpriteInstance {},
	Image15: class extends self.ISpriteInstance {},
	fly: class extends self.ISpriteInstance {},
	LeftPoint: class extends self.ISpriteInstance {},
	RightPoint: class extends self.ISpriteInstance {},
	ТекстДляМух: class extends self.ITextInstance {},
	МухаМеню: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Image18: class extends self.ISpriteInstance {},
	Image19: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Image20: class extends self.ISpriteInstance {},
	Image21: class extends self.ISpriteInstance {},
	Image22: class extends self.ISpriteInstance {},
	Image23: class extends self.ISpriteInstance {},
	Image24: class extends self.ISpriteInstance {},
	Image25: class extends self.ISpriteInstance {},
	Image26: class extends self.ISpriteInstance {},
	Image27: class extends self.ISpriteInstance {},
	Image28: class extends self.ISpriteInstance {},
	Image29: class extends self.ISpriteInstance {},
	Image30: class extends self.ISpriteInstance {},
	Image5: class extends self.ISpriteInstance {},
	Image31: class extends self.ISpriteInstance {},
	Image32: class extends self.ISpriteInstance {},
	Image33: class extends self.ISpriteInstance {},
	Image34: class extends self.ISpriteInstance {},
	Image35: class extends self.ISpriteInstance {},
	Image36: class extends self.ISpriteInstance {},
	Image37: class extends self.ISpriteInstance {},
	Image38: class extends self.ISpriteInstance {},
	Image39: class extends self.ISpriteInstance {},
	Image40: class extends self.ISpriteInstance {},
	Image41: class extends self.ISpriteInstance {},
	Image42: class extends self.ISpriteInstance {},
	Image43: class extends self.ISpriteInstance {},
	DialogBg: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	DialogText: class extends self.ITextInstance {},
	doorbell: class extends self.ISpriteInstance {},
	mamcat: class extends self.ISpriteInstance {},
	door: class extends self.ISpriteInstance {},
	green_frog: class extends self.ISpriteInstance {},
	green_frog_button: class extends self.ISpriteInstance {},
	purple_frog_button: class extends self.ISpriteInstance {},
	blue_frog_button: class extends self.ISpriteInstance {},
	purple_frog: class extends self.ISpriteInstance {},
	blue_frog: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	PricePinkFrog: class extends self.ITextInstance {},
	PriceBlueFrog: class extends self.ITextInstance {},
	button2: class extends self.ISpriteInstance {},
	balanceText: class extends self.ITextInstance {},
	Image16: class extends self.ISpriteInstance {},
	Image17: class extends self.ISpriteInstance {},
	Image44: class extends self.ISpriteInstance {},
	cactus: class extends self.ISpriteInstance {},
	Image46: class extends self.ISpriteInstance {},
	Image47: class extends self.ISpriteInstance {},
	Image48: class extends self.ISpriteInstance {},
	Image49: class extends self.ISpriteInstance {},
	Image50: class extends self.ISpriteInstance {},
	Image51: class extends self.ISpriteInstance {},
	Image52: class extends self.ISpriteInstance {},
	Image53: class extends self.ISpriteInstance {},
	cactus2: class extends self.ISpriteInstance {},
	Image54: class extends self.ISpriteInstance {},
	Image45: class extends self.ISpriteInstance {},
	Image55: class extends self.ISpriteInstance {},
	Image56: class extends self.ISpriteInstance {},
	Image57: class extends self.ISpriteInstance {},
	Image58: class extends self.ISpriteInstance {},
	Image59: class extends self.ISpriteInstance {},
	Image60: class extends self.ISpriteInstance {},
	Image61: class extends self.ISpriteInstance {},
	Image62: class extends self.ISpriteInstance {},
	Image63: class extends self.ISpriteInstance {},
	Image64: class extends self.ISpriteInstance {},
	Image65: class extends self.ISpriteInstance {},
	Image66: class extends self.ISpriteInstance {},
	Image67: class extends self.ISpriteInstance {},
	Image68: class extends self.ISpriteInstance {},
	Image69: class extends self.ISpriteInstance {},
	Image70: class extends self.ISpriteInstance {},
	Image71: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	Image72: class extends self.ISpriteInstance {}
}