const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.sliderbar,
		C3.Plugins.Browser,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.sliderbar.Cnds.OnChanged,
		C3.Plugins.sliderbar.Cnds.CompareValue
	];
};
self.C3_JsPropNameTable = [
	{Спрайт: 0},
	{Спрайт2: 0},
	{score: 0},
	{Миша: 0},
	{Куля: 0},
	{Спрайт3: 0},
	{Аудіо: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{textPrice: 0},
	{textGet: 0},
	{buttonGet: 0},
	{textBalance: 0},
	{Кнопка: 0},
	{Спрайт8: 0},
	{Текст2: 0},
	{Спрайт9: 0},
	{menu: 0},
	{Спрайт10: 0},
	{play: 0},
	{test: 0},
	{settings: 0},
	{exit: 0},
	{ПанельПромотки: 0},
	{Текст3: 0},
	{Браузер: 0},
	{randBonus: 0},
	{indexSkin: 0},
	{maxSkin: 0},
	{currentSkin: 0},
	{priceCurrentSkin: 0},
	{жовтийСлайм: 0},
	{синяРослина: 0},
	{зеленаРослина: 0},
	{равлик: 0},
	{летючаМиш: 0},
	{білаРетька: 0},
	{гарбуз: 0},
	{зеленийСлайм: 0},
	{volume: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	Миша: class extends self.IInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Аудіо: class extends self.IInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	textPrice: class extends self.ITextInstance {},
	textGet: class extends self.ITextInstance {},
	buttonGet: class extends self.ISpriteInstance {},
	textBalance: class extends self.ITextInstance {},
	Кнопка: class extends self.IButtonInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Текст2: class extends self.ITextInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	menu: class extends self.ITextInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	play: class extends self.ITextInstance {},
	test: class extends self.ITextInstance {},
	settings: class extends self.ITextInstance {},
	exit: class extends self.ITextInstance {},
	ПанельПромотки: class extends self.ISliderBarInstance {},
	Текст3: class extends self.ITextInstance {},
	Браузер: class extends self.IInstance {}
}